### PR TITLE
Add Continuous Integration

### PR DESCRIPTION
**Pull request by lucaslovato**
Solves #11 add a dotnet CI

### CODE REVIEW

**Comment by FredRanieri** [comment]
I think it is better we just comment `Facebook Test` instead delete because later we will use it.

**Comment by lucaslovato** [comment]
> I think it is better we just comment `Facebook Test` instead delete because later we will use it.

I was thinking about this and I would prefer to delete unused files for now and then re-add them later instead of comment the whole file, but if you think it's best can be done

**Comment by FredRanieri** [comment]
> > I think it is better we just comment `Facebook Test` instead delete because later we will use it.
> 
> I was thinking about this and I would prefer to delete unused files for now and then re-add them later instead of comment the whole file, but if you think it's best can be done

Nice, so let's delete but I think we would create an issue now `Enable Facebook Test` or `Improve Facebook Test` explaining that we delete because of X and what we need to do. Just to not forget it later.

**Comment by leonardo-brickabode** [comment]
> I think it is better we just comment `Facebook Test` instead delete because later we will use it.

I think that is better delete, for my experience, when we comment files we tend to forget about them. We can return the Facebook tests when we create new mockup data.

**Comment by leonardo-brickabode** [comment]
> > > I think it is better we just comment `Facebook Test` instead delete because later we will use it.
> > 
> > 
> > I was thinking about this and I would prefer to delete unused files for now and then re-add them later instead of comment the whole file, but if you think it's best can be done
> 
> Nice, so let's delete but I think we would create an issue now `Enable Facebook Test` or `Improve Facebook Test` explaining that we delete because of X and what we need to do. Just to not forget it later.

The issue was created here:
https://github.com/Marketing-Automation-Systems/jellyfish/issues/17

**Comment by lucaslovato** [comment]
Since uncrustify is given too much problem the CI will be added without it and then uncrustify bug will be solved on #19

**Pull request merged**
